# Generated by Django 2.1.7 on 2019-03-16 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barangmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=250)),
                ('nomor_barang', models.CharField(max_length=200)),
                ('peminjam', models.CharField(max_length=200)),
                ('kelas_peminjam', models.CharField(choices=[('X TKJ 1', 'X TKJ 1'), ('X TKJ 2', 'X TKJ 2'), ('X TKJ 3', 'X TKJ 3'), ('XI TKJ 1', 'XI TKJ 1'), ('XI TKJ 2', 'XI TKJ 2'), ('XI TKJ 3', 'XI TKJ 3'), ('XII TKJ 1', 'XII TKJ 1'), ('XII TKJ 2', 'XII TKJ 2'), ('XII TKJ 3', 'XII TKJ 3'), ('Kelas Lain', 'Kelas Lain')], default='Kelas Lain', max_length=50)),
                ('waktu_pinjam', models.DateTimeField(default=django.utils.timezone.now)),
                ('waktu_kembali', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
