# Generated by Django 2.1.7 on 2019-03-16 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190316_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodels',
            name='waktu_pinjam',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
